### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by Alex293**
Hi, it's this time of the year again ;), I simply bumped Batch and Mixpanel version, I don't foresee any impact.

### CODE REVIEW

**Comment by abarisain** [comment]
Thanks!

Would it be helpful to change both to `upToNextMajor`?

**Comment by Alex293** [comment]
That would be helpful indeed. I won’t be able to update the branch for a week though

**Comment by Alex293** [comment]
According to [Apple doc](https://developer.apple.com/documentation/packagedescription/package/dependency/package(id:from:))
`from` does the same thing as `upToNextMajor`, allowing minor and patch versions automatic upgrades. I needed to bump the major thought as Batch released 2.0

Sorry for the delay completely forgot about this.

**Comment by abarisain** [comment]
No worries, I wanted to do it myself but couldn't find time. Thanks

**Comment by abarisain** [comment]
Sorry, forgot to hit the merge button

Thanks for the PR!

**Comment by Alex293** [comment]
@abarisain do you mind publishing a release or at least tagging those changes ?

**Comment by abarisain** [comment]
I will! Just have to do the same for cocoapods and I'll tag a release (it will be a major one)

**Comment by abarisain** [comment]
4.0.0 has been tagged!

**Pull request merged**
